# Generated by Django 6.1.1 on 2026-09-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumStacked',
            fields=[
            ],
            options={
                'verbose_name': 'Album (stacked inline demo)',
                'verbose_name_plural': 'Albums (stacked inline demo)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.album',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.album')),
            ],
        ),
    ]
