# Generated by Django 6.1.1 on 2026-09-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
